const jwt = require('jsonwebtoken');
const JWT_SECRET = process.env.JWT_SECRET || '';
const ROLE_TIERS = { contributor: 1, editor: 2, admin: 3 };
function normalizeRole(role) { if (!role || typeof role !== 'string') return ''; return role.trim().toLowerCase(); }
function getRoleTier(role) { return ROLE_TIERS[normalizeRole(role)] || 0; }
function parseCookies(header) { const cookies = {}; if (!header || typeof header !== 'string') return cookies; for (const part of header.split(';')) { const index = part.indexOf('='); if (index === -1) continue; const key = part.slice(0,index).trim(); const value = part.slice(index+1).trim(); if (key) { try { cookies[key] = decodeURIComponent(value); } catch { cookies[key] = value; } } } return cookies; }
function authenticateJwt(req,res,next) { const authHeader=req.headers.authorization||req.headers.Authorization; const cookies=parseCookies(req.headers.cookie); const token=authHeader&&typeof authHeader==='string'&&authHeader.toLowerCase().startsWith('bearer ')?authHeader.substring(7).trim():cookies.cms_token; if(!token)return res.status(401).json({error:'Unauthorized',message:'Authentication is required'}); const secret=process.env.JWT_SECRET; if(!secret||secret.length<32)return res.status(500).json({error:'Internal Server Error',message:'Authentication is not configured correctly'}); try{const decoded=jwt.verify(token,secret,{issuer:process.env.JWT_ISSUER||'961-media-cms',audience:process.env.JWT_AUDIENCE||'961-media-dashboard'});const userId=decoded.id||decoded.userId||decoded.sub;const userRole=decoded.role;if(!userId||!userRole)return res.status(401).json({error:'Unauthorized',message:'Invalid authentication token'});req.user={id:userId,role:userRole,...decoded};req.authenticatedUser=req.user;next();}catch(err){return res.status(401).json({error:'Unauthorized',message:'Invalid or expired authentication token'});}}
function requireRole(allowedRolesOrMinTier){return(req,res,next)=>{if(!req.user||!req.user.role)return res.status(401).json({error:'Unauthorized',message:'User authentication required'});const userRole=req.user.role;const userTier=getRoleTier(userRole);let isAllowed=false;if(Array.isArray(allowedRolesOrMinTier)){const normalizedAllowed=allowedRolesOrMinTier.map(r=>normalizeRole(r));isAllowed=normalizedAllowed.includes(normalizeRole(userRole));}else if(typeof allowedRolesOrMinTier==='string'){const minRole=normalizeRole(allowedRolesOrMinTier);const minTier=ROLE_TIERS[minRole]||0;isAllowed=minTier>0?userTier>=minTier:normalizeRole(userRole)===minRole;}if(!isAllowed)return res.status(403).json({error:'Forbidden',message:`Insufficient permissions. Role '${userRole}' is not authorized for this operation.`});next();};}
function checkArticlePublishingRole(req,res,next){if(req.body&&typeof req.body.status==='string'&&req.body.status.trim().toLowerCase()==='published'){const userRole=req.user?req.user.role:'';if(getRoleTier(userRole)<ROLE_TIERS.editor)return res.status(403).json({error:'Forbidden',message:'Publishing articles requires Editor or Admin role.'});}next();}
function auditLogger(req,res,next){if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const originalSend=res.send;res.send=function(...args){if(!res._auditLogged){res._auditLogged=true;const userId=req.user?(req.user.id||req.user.userId||req.user.sub||'unknown'):'unauthenticated';const userRole=req.user?req.user.role:'unknown';console.log(`[MUTATION AUDIT] User ID: ${userId} | Role: ${userRole} | Action: ${req.method} ${req.originalUrl||req.url} | Status: ${res.statusCode}`);}return originalSend.apply(res,args);};}next();}
module.exports={authenticateJwt,requireRole,checkArticlePublishingRole,auditLogger,JWT_SECRET,ROLE_TIERS};
