const crypto = require('crypto');
const db = require('../db');

// In-memory backing array when database is not connected
let inMemoryPipelines = [];

/**
 * Creates a new content pipeline record
 * @param {Object} params
 * @param {string} params.topic
 * @param {string} params.category
 * @param {string[]} [params.headlines]
 * @returns {Promise<Object>} Created pipeline record
 */
async function createPipeline({ topic, category, headlines = [] }) {
  const id = crypto.randomUUID();
  const now = new Date().toISOString();
  const status = headlines.length > 0 ? 'headlines_generated' : 'draft';

  const record = {
    id,
    topic,
    category,
    chosen_headline: null,
    article_body: null,
    social_summary: null,
    ig_caption: null,
    carousel_slides: [],
    main_image_path: null,
    slide_image_paths: [],
    rendered_assets: {},
    headlines,
    status,
    created_at: now,
    updated_at: now
  };

  try {
    const res = await db.query(
      `INSERT INTO content_pipeline 
       (id, topic, category, status, carousel_slides, slide_image_paths, rendered_assets, created_at, updated_at) 
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) 
       RETURNING *`,
      [
        id,
        topic,
        category,
        status,
        JSON.stringify(record.carousel_slides),
        JSON.stringify(record.slide_image_paths),
        JSON.stringify(record.rendered_assets),
        now,
        now
      ]
    );

    if (res && res.rows && res.rows[0]) {
      const dbRow = res.rows[0];
      return formatRecord({ ...dbRow, headlines });
    }
  } catch (err) {
    // Database query failed or unavailable, fallback to in-memory store
  }

  inMemoryPipelines.push(record);
  return record;
}

/**
 * Updates a pipeline with draft content generated by Gemini
 * @param {string} id
 * @param {Object} content
 * @returns {Promise<Object|null>}
 */
async function updatePipelineDraft(id, { chosen_headline, article_body, social_summary, ig_caption, carousel_slides }) {
  const now = new Date().toISOString();
  const status = 'content_ready';

  try {
    const res = await db.query(
      `UPDATE content_pipeline 
       SET chosen_headline = $1, article_body = $2, social_summary = $3, ig_caption = $4, 
           carousel_slides = $5, status = $6, updated_at = $7 
       WHERE id = $8 
       RETURNING *`,
      [
        chosen_headline,
        article_body,
        social_summary,
        ig_caption,
        JSON.stringify(carousel_slides || []),
        status,
        now,
        id
      ]
    );

    if (res && res.rows && res.rows[0]) {
      return formatRecord(res.rows[0]);
    }
  } catch (err) {
    // Fallback
  }

  const existing = inMemoryPipelines.find(p => p.id === id);
  if (!existing) return null;

  existing.chosen_headline = chosen_headline;
  existing.article_body = article_body;
  existing.social_summary = social_summary;
  existing.ig_caption = ig_caption;
  existing.carousel_slides = carousel_slides || [];
  existing.status = status;
  existing.updated_at = now;

  return existing;
}

/**
 * Updates a pipeline with media image paths
 * @param {string} id
 * @param {Object} mediaData
 * @param {string} [mediaData.main_image_path]
 * @param {string[]} [mediaData.slide_image_paths]
 * @returns {Promise<Object|null>}
 */
async function updatePipelineMedia(id, { main_image_path, slide_image_paths }) {
  const now = new Date().toISOString();

  try {
    const res = await db.query(
      `UPDATE content_pipeline 
       SET main_image_path = COALESCE($1, main_image_path), 
           slide_image_paths = COALESCE($2, slide_image_paths), 
           updated_at = $3 
       WHERE id = $4 
       RETURNING *`,
      [
        main_image_path || null,
        slide_image_paths ? JSON.stringify(slide_image_paths) : null,
        now,
        id
      ]
    );

    if (res && res.rows && res.rows[0]) {
      return formatRecord(res.rows[0]);
    }
  } catch (err) {
    // Fallback
  }

  const existing = inMemoryPipelines.find(p => p.id === id);
  if (!existing) return null;

  if (main_image_path !== undefined) existing.main_image_path = main_image_path;
  if (slide_image_paths !== undefined) existing.slide_image_paths = slide_image_paths;
  existing.updated_at = now;

  return existing;
}

/**
 * Sets pipeline status to published and updates rendered assets
 * @param {string} id
 * @param {Object} publishData
 * @param {Object} [publishData.rendered_assets]
 * @returns {Promise<Object|null>}
 */
async function updatePipelinePublish(id, { rendered_assets }) {
  const now = new Date().toISOString();
  const status = 'published';

  try {
    const res = await db.query(
      `UPDATE content_pipeline 
       SET rendered_assets = COALESCE($1, rendered_assets), 
           status = $2, 
           updated_at = $3 
       WHERE id = $4 
       RETURNING *`,
      [
        rendered_assets ? JSON.stringify(rendered_assets) : null,
        status,
        now,
        id
      ]
    );

    if (res && res.rows && res.rows[0]) {
      return formatRecord(res.rows[0]);
    }
  } catch (err) {
    // Fallback
  }

  const existing = inMemoryPipelines.find(p => p.id === id);
  if (!existing) return null;

  if (rendered_assets !== undefined) existing.rendered_assets = rendered_assets;
  existing.status = status;
  existing.updated_at = now;

  return existing;
}

/**
 * Retrieves pipeline by ID
 * @param {string} id
 * @returns {Promise<Object|null>}
 */
async function getPipelineById(id) {
  try {
    const res = await db.query(`SELECT * FROM content_pipeline WHERE id = $1`, [id]);
    if (res && res.rows && res.rows[0]) {
      return formatRecord(res.rows[0]);
    }
  } catch (err) {
    // Fallback
  }

  const found = inMemoryPipelines.find(p => p.id === id);
  return found || null;
}

/**
 * Returns all pipelines
 * @returns {Promise<Array>}
 */
async function getAllPipelines() {
  try {
    const res = await db.query(`SELECT * FROM content_pipeline ORDER BY created_at DESC`);
    if (res && res.rows) {
      return res.rows.map(formatRecord);
    }
  } catch (err) {
    // Fallback
  }

  return [...inMemoryPipelines].sort((a, b) => new Date(b.created_at) - new Date(a.created_at));
}

/**
 * Clears in-memory store for testing
 */
async function clearStore() {
  inMemoryPipelines = [];
  try {
    await db.query(`TRUNCATE TABLE content_pipeline`);
  } catch (err) {
    // Ignore
  }
}

function formatRecord(row) {
  if (!row) return null;
  return {
    id: row.id,
    pipeline_id: row.id,
    topic: row.topic,
    category: row.category,
    chosen_headline: row.chosen_headline || null,
    article_body: row.article_body || null,
    social_summary: row.social_summary || null,
    ig_caption: row.ig_caption || null,
    carousel_slides: typeof row.carousel_slides === 'string' ? JSON.parse(row.carousel_slides) : (row.carousel_slides || []),
    main_image_path: row.main_image_path || null,
    slide_image_paths: typeof row.slide_image_paths === 'string' ? JSON.parse(row.slide_image_paths) : (row.slide_image_paths || []),
    rendered_assets: typeof row.rendered_assets === 'string' ? JSON.parse(row.rendered_assets) : (row.rendered_assets || {}),
    headlines: row.headlines || [],
    status: row.status,
    created_at: row.created_at,
    updated_at: row.updated_at
  };
}

module.exports = {
  createPipeline,
  updatePipelineDraft,
  updatePipelineMedia,
  updatePipelinePublish,
  getPipelineById,
  getAllPipelines,
  clearStore
};
